os: linux
language: python
python:
  - "3.7"
git: 
  - fetch origin
  - rebase origin/master
  - checkout testfeature

addons:
  chrome: stable
cache: pip
install:
  - pip install -r requirements.txt
script:
  - ./runTest.sh
